[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.26"
optimizer = true
optimizer_runs = 1000000
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@openzeppelin/contracts/=lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "solmate/=lib/v4-core/lib/solmate/",
    "@uniswap/v4-core/=lib/v4-core/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
